import {
  Apple, Zap, Heart, Star, Crown, Ghost, Snowflake, TreePine,
  Clover, Flower2, Fish, Car, Bike, Plane, Rocket, Trophy,
  Bell, Key, Lock, Glasses, Clock, Gift, Lightbulb, Camera,
  Headphones, Coffee, Pizza, IceCream2, Candy, Flame, Droplet,
  Gem, Compass, Scissors, Shield, Anchor, Hammer, Flag,
  Bone, Music, Wand2, Dices, Pencil, Sparkles, ThumbsUp,
  Sun, Moon, Cat, Dog, Bird, Bug, Sprout, Globe, Footprints,
  Smile, Umbrella, CloudRain,
  LucideIcon
} from 'lucide-react';

export interface SymbolDef {
  id: number;
  name: string;
  icon: LucideIcon;
  color: string;
  bgTint: string;
}

export const SYMBOLS: SymbolDef[] = [
  { id: 0, name: '사과', icon: Apple, color: '#ef4444', bgTint: '#fee2e2' },
  { id: 1, name: '번개', icon: Zap, color: '#eab308', bgTint: '#fef9c3' },
  { id: 2, name: '하트', icon: Heart, color: '#f43f5e', bgTint: '#ffe4e6' },
  { id: 3, name: '별', icon: Star, color: '#f59e0b', bgTint: '#fef3c7' },
  { id: 4, name: '왕관', icon: Crown, color: '#d97706', bgTint: '#fef3c7' },
  { id: 5, name: '유령', icon: Ghost, color: '#8b5cf6', bgTint: '#ede9fe' },
  { id: 6, name: '눈송이', icon: Snowflake, color: '#0ea5e9', bgTint: '#e0f2fe' },
  { id: 7, name: '나무', icon: TreePine, color: '#16a34a', bgTint: '#dcfce7' },
  { id: 8, name: '클로버', icon: Clover, color: '#15803d', bgTint: '#dcfce7' },
  { id: 9, name: '꽃', icon: Flower2, color: '#ec4899', bgTint: '#fce7f3' },
  { id: 10, name: '물고기', icon: Fish, color: '#06b6d4', bgTint: '#cffafe' },
  { id: 11, name: '자동차', icon: Car, color: '#dc2626', bgTint: '#fee2e2' },
  { id: 12, name: '자전거', icon: Bike, color: '#059669', bgTint: '#d1fae5' },
  { id: 13, name: '비행기', icon: Plane, color: '#2563eb', bgTint: '#dbeafe' },
  { id: 14, name: '로켓', icon: Rocket, color: '#ea580c', bgTint: '#ffedd5' },
  { id: 15, name: '트로피', icon: Trophy, color: '#ca8a04', bgTint: '#fef08a' },
  { id: 16, name: '종', icon: Bell, color: '#eab308', bgTint: '#fef9c3' },
  { id: 17, name: '열쇠', icon: Key, color: '#b45309', bgTint: '#fef3c7' },
  { id: 18, name: '자물쇠', icon: Lock, color: '#64748b', bgTint: '#f1f5f9' },
  { id: 19, name: '안경', icon: Glasses, color: '#334155', bgTint: '#e2e8f0' },
  { id: 20, name: '시계', icon: Clock, color: '#0284c7', bgTint: '#e0f2fe' },
  { id: 21, name: '선물', icon: Gift, color: '#e11d48', bgTint: '#ffe4e6' },
  { id: 22, name: '전구', icon: Lightbulb, color: '#eab308', bgTint: '#fef9c3' },
  { id: 23, name: '카메라', icon: Camera, color: '#475569', bgTint: '#f1f5f9' },
  { id: 24, name: '헤드폰', icon: Headphones, color: '#7c3aed', bgTint: '#ede9fe' },
  { id: 25, name: '커피', icon: Coffee, color: '#78350f', bgTint: '#fef3c7' },
  { id: 26, name: '피자', icon: Pizza, color: '#f97316', bgTint: '#ffedd5' },
  { id: 27, name: '아이스크림', icon: IceCream2, color: '#f43f5e', bgTint: '#ffe4e6' },
  { id: 28, name: '사탕', icon: Candy, color: '#d946ef', bgTint: '#fae8ff' },
  { id: 29, name: '불꽃', icon: Flame, color: '#ef4444', bgTint: '#fee2e2' },
  { id: 30, name: '물방울', icon: Droplet, color: '#3b82f6', bgTint: '#dbeafe' },
  { id: 31, name: '보석', icon: Gem, color: '#06b6d4', bgTint: '#cffafe' },
  { id: 32, name: '나침반', icon: Compass, color: '#d97706', bgTint: '#fef3c7' },
  { id: 33, name: '가위', icon: Scissors, color: '#ea580c', bgTint: '#ffedd5' },
  { id: 34, name: '방패', icon: Shield, color: '#4f46e5', bgTint: '#e0e7ff' },
  { id: 35, name: '닻', icon: Anchor, color: '#1e3a8a', bgTint: '#dbeafe' },
  { id: 36, name: '망치', icon: Hammer, color: '#854d0e', bgTint: '#fef9c3' },
  { id: 37, name: '깃발', icon: Flag, color: '#dc2626', bgTint: '#fee2e2' },
  { id: 38, name: '뼈다귀', icon: Bone, color: '#94a3b8', bgTint: '#f8fafc' },
  { id: 39, name: '음표', icon: Music, color: '#9333ea', bgTint: '#f3e8ff' },
  { id: 40, name: '마법봉', icon: Wand2, color: '#a855f7', bgTint: '#f3e8ff' },
  { id: 41, name: '주사위', icon: Dices, color: '#3b82f6', bgTint: '#dbeafe' },
  { id: 42, name: '연필', icon: Pencil, color: '#f59e0b', bgTint: '#fef3c7' },
  { id: 43, name: '별빛', icon: Sparkles, color: '#eab308', bgTint: '#fef9c3' },
  { id: 44, name: '엄지척', icon: ThumbsUp, color: '#10b981', bgTint: '#d1fae5' },
  { id: 45, name: '태양', icon: Sun, color: '#f97316', bgTint: '#ffedd5' },
  { id: 46, name: '달', icon: Moon, color: '#6366f1', bgTint: '#e0e7ff' },
  { id: 47, name: '고양이', icon: Cat, color: '#ea580c', bgTint: '#ffedd5' },
  { id: 48, name: '강아지', icon: Dog, color: '#9a3412', bgTint: '#ffedd5' },
  { id: 49, name: '새', icon: Bird, color: '#0284c7', bgTint: '#e0f2fe' },
  { id: 50, name: '무당벌레', icon: Bug, color: '#e11d48', bgTint: '#ffe4e6' },
  { id: 51, name: '새싹', icon: Sprout, color: '#22c55e', bgTint: '#dcfce7' },
  { id: 52, name: '지구', icon: Globe, color: '#0891b2', bgTint: '#cffafe' },
  { id: 53, name: '발자국', icon: Footprints, color: '#64748b', bgTint: '#f1f5f9' },
  { id: 54, name: '스마일', icon: Smile, color: '#eab308', bgTint: '#fef9c3' },
  { id: 55, name: '우산', icon: Umbrella, color: '#0284c7', bgTint: '#e0f2fe' },
  { id: 56, name: '비구름', icon: CloudRain, color: '#475569', bgTint: '#f1f5f9' },
];
